import Link from 'next/link';import {formatINR} from '@/lib/money';import type {Donation,Transaction} from '@/types/domain';
export function DashboardCard({title,value,note}:{title:string;value:string;note?:string;key?:string}){return <div className="card"><small>{title}</small><h2>{value}</h2>{note&&<p>{note}</p>}</div>}
export function ChartCard({title}:{title:string;key?:string}){return <div className="card"><h3>{title}</h3><div className="chart">{[30,70,45,90,55,80,65].map((h,i)=><span key={i} className="bar" style={{height:h+'%'}} />)}</div></div>}
export function SearchBar(){return <div className="card"><input className="input" placeholder="Search name, mobile, receipt no, transaction ID" /></div>}
export function DateFilter(){return <div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))'}}><input className="input" type="date"/><input className="input" type="date"/><button className="btn">Apply filters</button></div>}
export function AdminSidebar(){const links=['dashboard','donors','donations/new','expenses','withdrawals','transactions','reports','settings'];return <aside className="sidebar"><h2>🕉️ GCM</h2>{links.map(l=><Link key={l} href={`/admin/${l}`}>{l.replace('/new','').replace('-',' ')}</Link>)}</aside>}
export function MobileNavigation(){return <nav className="bottom-nav"><Link href="/admin/dashboard">Dashboard</Link><Link href="/admin/donors">Donations</Link><Link href="/admin/expenses">Expenses</Link><Link href="/admin/reports">Reports</Link><Link href="/admin/settings">More</Link></nav>}
export function AdminLayout({children}:{children:React.ReactNode}){return <div className="admin"><AdminSidebar/><main className="container">{children}</main><MobileNavigation/></div>}
export function DonationTable({rows}:{rows:Donation[]}){return <div className="table-wrap"><table className="table"><thead><tr>{['Receipt No','Donor Name','Mobile','Amount','Payment Method','Status','Date','Actions'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(d=><tr key={d.id}><td>{d.receiptNumber}</td><td>{d.donorName}</td><td>{d.mobile}</td><td>{formatINR(d.amount)}</td><td>{d.paymentMethod}</td><td><span className="badge">{d.status}</span></td><td>{new Date(d.createdAt).toLocaleDateString('en-IN')}</td><td><Link href={`/receipt/${d.receiptNumber}`}>Receipt</Link></td></tr>)}</tbody></table></div>}
export const DonorTable=DonationTable;
export function TransactionTable({rows}:{rows:Transaction[]}){return <div className="table-wrap"><table className="table"><thead><tr>{['Date','Transaction ID','Type','Description','Income','Expense','Balance','Created By'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(t=><tr key={t.id}><td>{new Date(t.date).toLocaleDateString('en-IN')}</td><td>{t.id}</td><td>{t.type}</td><td>{t.description}</td><td>{formatINR(t.income)}</td><td>{formatINR(t.expense)}</td><td>{formatINR(t.balance)}</td><td>{t.createdBy}</td></tr>)}</tbody></table></div>}
export function PaymentStatus({status}:{status:string}){return <div className="notice"><b>Payment status:</b> {status}. Mock mode is for development only and never represents real money.</div>}
export function ConfirmDialog(){return <div className="notice">Completing a withdrawal requires confirmation; only APPROVED or COMPLETED withdrawals affect balance.</div>}
export function FileUpload(){return <input className="input" type="file" accept="image/png,image/jpeg,application/pdf" />}
